create extension if not exists pgcrypto with schema extensions;

create schema if not exists app_private;
revoke all on schema app_private from anon, authenticated, public;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'admin_role') then
    create type public.admin_role as enum ('super_admin', 'admin', 'sales');
  end if;
  if not exists (select 1 from pg_type where typname = 'lead_status') then
    create type public.lead_status as enum ('new', 'in_progress', 'qualified', 'closed');
  end if;
  if not exists (select 1 from pg_type where typname = 'lead_priority') then
    create type public.lead_priority as enum ('low', 'medium', 'high');
  end if;
  if not exists (select 1 from pg_type where typname = 'lead_type') then
    create type public.lead_type as enum ('contact', 'newsletter', 'careers', 'demo');
  end if;
end $$;

create or replace function app_private.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  full_name text not null default '',
  role public.admin_role not null default 'sales',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_profiles_email_lower check (email = lower(email)),
  constraint admin_profiles_username_nonempty check (length(trim(username)) > 0)
);

create trigger admin_profiles_set_updated_at
before update on public.admin_profiles
for each row execute function app_private.set_updated_at();

create or replace function app_private.current_admin_role()
returns public.admin_role
language sql
stable
security definer
set search_path = ''
as $$
  select p.role
  from public.admin_profiles p
  where p.user_id = auth.uid()
    and p.is_active = true
  limit 1
$$;

create or replace function app_private.current_admin_is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_profiles p
    where p.user_id = auth.uid()
      and p.is_active = true
  )
$$;

create or replace function app_private.current_admin_has_role(allowed_roles public.admin_role[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(app_private.current_admin_role() = 'super_admin'::public.admin_role, false)
      or coalesce(app_private.current_admin_role() = any(allowed_roles), false)
$$;

grant usage on schema app_private to authenticated;
grant execute on function app_private.current_admin_role() to anon, authenticated;
grant execute on function app_private.current_admin_is_active() to anon, authenticated;
grant execute on function app_private.current_admin_has_role(public.admin_role[]) to anon, authenticated;

create table public.contact_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text not null default '',
  service text not null default '',
  budget text not null default '',
  message text not null,
  status public.lead_status not null default 'new',
  priority public.lead_priority not null default 'medium',
  assigned_to uuid references public.admin_profiles(user_id) on delete set null,
  next_followup_at timestamptz,
  ip_address text not null default 'unknown',
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  status public.lead_status not null default 'new',
  priority public.lead_priority not null default 'medium',
  assigned_to uuid references public.admin_profiles(user_id) on delete set null,
  next_followup_at timestamptz,
  ip_address text not null default 'unknown',
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.career_applications (
  id bigint generated by default as identity primary key,
  job_title text not null,
  name text not null,
  email text not null,
  linkedin text not null default '',
  portfolio text not null default '',
  cover_letter text not null,
  resume_original_name text not null default '',
  resume_stored_file_name text not null default '',
  resume_mime_type text not null default '',
  resume_size bigint not null default 0,
  resume_path text not null default '',
  status public.lead_status not null default 'new',
  priority public.lead_priority not null default 'medium',
  assigned_to uuid references public.admin_profiles(user_id) on delete set null,
  next_followup_at timestamptz,
  ip_address text not null default 'unknown',
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.demo_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  school text not null,
  phone text not null,
  status public.lead_status not null default 'new',
  priority public.lead_priority not null default 'medium',
  assigned_to uuid references public.admin_profiles(user_id) on delete set null,
  next_followup_at timestamptz,
  source_path text not null default '/showcase',
  ip_address text not null default 'unknown',
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lead_notes (
  id bigint generated by default as identity primary key,
  lead_type public.lead_type not null,
  lead_id bigint not null,
  author_user_id uuid references public.admin_profiles(user_id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

create table public.testimonials (
  id bigint generated by default as identity primary key,
  quote text not null,
  name text not null,
  role text not null,
  company text not null,
  avatar text not null default '',
  result text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.portfolio_projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  emoji text not null default '',
  tags jsonb not null default '[]'::jsonb,
  image text not null default '',
  description text not null,
  result text not null,
  overview text not null,
  challenge text not null,
  solution text not null,
  timeline text not null,
  team text not null,
  services text not null,
  featured boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.portfolio_results (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.portfolio_projects(id) on delete cascade,
  metric text not null,
  label text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.feature_sections (
  id uuid primary key default gen_random_uuid(),
  section_order integer not null default 0,
  section_key text not null unique,
  icon text not null default 'SparklesIcon',
  title text not null,
  subtitle text not null default '',
  description text not null default '',
  features jsonb not null default '[]'::jsonb,
  highlight text not null default '',
  design_insight_label text not null default 'Design Decision',
  design_insight_description text not null default '',
  screen_image text not null default '',
  screen_alt text not null default '',
  accent_color text not null default '#6366F1',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.rate_limit_counters (
  bucket_key text not null,
  window_start bigint not null,
  count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (bucket_key, window_start)
);

create table public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.admin_profiles(user_id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text not null default 'unknown',
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

create index contact_leads_created_at_idx on public.contact_leads(created_at desc);
create index contact_leads_email_idx on public.contact_leads(email);
create index contact_leads_status_idx on public.contact_leads(status);
create index newsletter_subscribers_created_at_idx on public.newsletter_subscribers(created_at desc);
create index newsletter_subscribers_email_idx on public.newsletter_subscribers(email);
create index career_applications_created_at_idx on public.career_applications(created_at desc);
create index career_applications_email_idx on public.career_applications(email);
create index career_applications_job_title_idx on public.career_applications(job_title);
create index demo_requests_created_at_idx on public.demo_requests(created_at desc);
create index demo_requests_phone_idx on public.demo_requests(phone);
create index lead_notes_ref_idx on public.lead_notes(lead_type, lead_id, created_at desc);
create index testimonials_sort_idx on public.testimonials(sort_order, id desc);
create index portfolio_projects_sort_idx on public.portfolio_projects(sort_order, id desc);
create index portfolio_results_project_idx on public.portfolio_results(project_id, sort_order, id);
create index feature_sections_order_idx on public.feature_sections(section_order, id);
create index admin_activity_logs_created_at_idx on public.admin_activity_logs(created_at desc);
create index rate_limit_counters_window_idx on public.rate_limit_counters(window_start);

create trigger contact_leads_set_updated_at
before update on public.contact_leads
for each row execute function app_private.set_updated_at();

create trigger newsletter_subscribers_set_updated_at
before update on public.newsletter_subscribers
for each row execute function app_private.set_updated_at();

create trigger career_applications_set_updated_at
before update on public.career_applications
for each row execute function app_private.set_updated_at();

create trigger demo_requests_set_updated_at
before update on public.demo_requests
for each row execute function app_private.set_updated_at();

create trigger testimonials_set_updated_at
before update on public.testimonials
for each row execute function app_private.set_updated_at();

create trigger portfolio_projects_set_updated_at
before update on public.portfolio_projects
for each row execute function app_private.set_updated_at();

create trigger portfolio_results_set_updated_at
before update on public.portfolio_results
for each row execute function app_private.set_updated_at();

create trigger feature_sections_set_updated_at
before update on public.feature_sections
for each row execute function app_private.set_updated_at();

create or replace function app_private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(coalesce(new.email, ''));
begin
  if normalized_email = 'techmigos.global@gmail.com' then
    insert into public.admin_profiles (user_id, username, email, full_name, role, is_active)
    values (
      new.id,
      'techmigos-global',
      normalized_email,
      coalesce(new.raw_user_meta_data ->> 'full_name', 'Techmigos Global'),
      'super_admin',
      true
    )
    on conflict (user_id) do update
      set email = excluded.email,
          role = 'super_admin',
          is_active = true,
          updated_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_admin_profile on auth.users;
create trigger on_auth_user_created_admin_profile
after insert on auth.users
for each row execute function app_private.handle_new_auth_user();

grant usage on schema public to anon, authenticated;
grant select on public.feature_sections to anon, authenticated;
grant select, insert, update, delete on
  public.admin_profiles,
  public.contact_leads,
  public.newsletter_subscribers,
  public.career_applications,
  public.demo_requests,
  public.lead_notes,
  public.testimonials,
  public.portfolio_projects,
  public.portfolio_results,
  public.feature_sections,
  public.admin_activity_logs
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.admin_profiles enable row level security;
alter table public.contact_leads enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.career_applications enable row level security;
alter table public.demo_requests enable row level security;
alter table public.lead_notes enable row level security;
alter table public.testimonials enable row level security;
alter table public.portfolio_projects enable row level security;
alter table public.portfolio_results enable row level security;
alter table public.feature_sections enable row level security;
alter table public.rate_limit_counters enable row level security;
alter table public.admin_activity_logs enable row level security;

create policy "admin_profiles_select_admins"
on public.admin_profiles
for select
to authenticated
using (app_private.current_admin_is_active());

create policy "admin_profiles_update_super_admins"
on public.admin_profiles
for update
to authenticated
using (app_private.current_admin_has_role(array['super_admin']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['super_admin']::public.admin_role[]));

create policy "admin_profiles_insert_super_admins"
on public.admin_profiles
for insert
to authenticated
with check (app_private.current_admin_has_role(array['super_admin']::public.admin_role[]));

create policy "admin_profiles_delete_super_admins"
on public.admin_profiles
for delete
to authenticated
using (app_private.current_admin_has_role(array['super_admin']::public.admin_role[]));

create policy "contact_leads_admin_access"
on public.contact_leads
for all
to authenticated
using (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]));

create policy "newsletter_subscribers_admin_access"
on public.newsletter_subscribers
for all
to authenticated
using (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]));

create policy "career_applications_admin_access"
on public.career_applications
for all
to authenticated
using (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]));

create policy "demo_requests_admin_access"
on public.demo_requests
for all
to authenticated
using (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]));

create policy "lead_notes_admin_access"
on public.lead_notes
for all
to authenticated
using (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin','sales']::public.admin_role[]));

create policy "testimonials_public_read_active"
on public.testimonials
for select
to anon, authenticated
using (is_active = true or app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "testimonials_admin_write"
on public.testimonials
for all
to authenticated
using (app_private.current_admin_has_role(array['admin']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "portfolio_projects_public_read_active"
on public.portfolio_projects
for select
to anon, authenticated
using (is_active = true or app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "portfolio_projects_admin_write"
on public.portfolio_projects
for all
to authenticated
using (app_private.current_admin_has_role(array['admin']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "portfolio_results_public_read_active_projects"
on public.portfolio_results
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.portfolio_projects p
    where p.id = portfolio_results.project_id
      and (p.is_active = true or app_private.current_admin_has_role(array['admin']::public.admin_role[]))
  )
);

create policy "portfolio_results_admin_write"
on public.portfolio_results
for all
to authenticated
using (app_private.current_admin_has_role(array['admin']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "feature_sections_public_read_active"
on public.feature_sections
for select
to anon, authenticated
using (is_active = true or app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "feature_sections_admin_write"
on public.feature_sections
for all
to authenticated
using (app_private.current_admin_has_role(array['admin']::public.admin_role[]))
with check (app_private.current_admin_has_role(array['admin']::public.admin_role[]));

create policy "admin_activity_logs_super_admin_read"
on public.admin_activity_logs
for select
to authenticated
using (app_private.current_admin_has_role(array['super_admin']::public.admin_role[]));

insert into public.feature_sections (
  section_order,
  section_key,
  icon,
  title,
  subtitle,
  description,
  features,
  highlight,
  design_insight_label,
  design_insight_description,
  screen_image,
  screen_alt,
  accent_color,
  is_active
)
values (
  0,
  'schooldesk-overview',
  'AcademicCapIcon',
  'SchoolDesk Overview',
  'One operating system for school teams',
  'A live-editable showcase section seeded by the Supabase migration.',
  '[{"text":"Supabase-backed content"},{"text":"Admin-managed screenshots"},{"text":"RLS-protected editing"}]'::jsonb,
  'Ready for real showcase content.',
  'Backend Decision',
  'Showcase content is stored in Supabase with public reads and admin-only writes.',
  '',
  'SchoolDesk app screen',
  '#2563EB',
  true
) on conflict (section_key) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('career-resumes', 'career-resumes', false, 5242880, array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]),
  ('showcase-screenshots', 'showcase-screenshots', true, 10485760, array[
    'image/png',
    'image/jpeg',
    'image/webp',
    'image/gif'
  ])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "showcase_screenshots_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'showcase-screenshots');

create policy "showcase_screenshots_admin_write"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'showcase-screenshots'
  and app_private.current_admin_has_role(array['admin']::public.admin_role[])
)
with check (
  bucket_id = 'showcase-screenshots'
  and app_private.current_admin_has_role(array['admin']::public.admin_role[])
);

create policy "career_resumes_admin_read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'career-resumes'
  and app_private.current_admin_has_role(array['admin','sales']::public.admin_role[])
);
